// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_SAMILDELACRUZ.DAL;

#nullable disable

namespace P1_AP1_SAMILDELACRUZ.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251011015501_MigracionesDetails")]
    partial class MigracionesDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("Huacales");
                });

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Rojo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_SAMILDELACRUZ.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradaHuacalDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_SAMILDELACRUZ.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("EntradaHuacalDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradaHuacalDetalle");
                });

            modelBuilder.Entity("P1_AP1_SAMILDELACRUZ.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradaHuacalDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
